name: AdvancedDiscord
version: '1.0-SNAPSHOT'
main: org.shakespeare.advanceddiscord.AdvancedDiscord
api-version: '1.21'
authors: [Shakespeare]
description: An advanced and easy discord-minecraft plugin!
website: github.com/ishakespearee/advanceddiscord
commands:
  adabout:
  advanceddiscordabout:
  discord:
  advanceddiscord:
  ad:
